admin_lte.home:
    path:     /
    defaults: { _controller: AdminLTEAdminBundle:Default:home }

admin_lte.form_general:
    path:     /form/general
    defaults: { _controller: AdminLTEAdminBundle:Default:formGeneral }

admin_lte.form_advanced:
    path:     /form/advanced
    defaults: { _controller: AdminLTEAdminBundle:Default:formAdvanced }

admin_lte.form_editors:
    path:     /form/editors
    defaults: { _controller: AdminLTEAdminBundle:Default:formEditors }