admin_lte.home:
    path:     /
    defaults: { _controller: AdminLTEAdminBundle:Default:home }

# Form
admin_lte.form_general:
    path:     /form/general
    defaults: { _controller: AdminLTEAdminBundle:Form:general }

admin_lte.form_advanced:
    path:     /form/advanced
    defaults: { _controller: AdminLTEAdminBundle:Form:advanced }

admin_lte.form_editors:
    path:     /form/editors
    defaults: { _controller: AdminLTEAdminBundle:Form:editors }

# Table
admin_lte.simple_table:
    path:     /table/simple
    defaults: { _controller: AdminLTEAdminBundle:Table:simple }

admin_lte.data_table:
    path:     /table/data
    defaults: { _controller: AdminLTEAdminBundle:Table:data }

# User
admin_lte.index_user:
    path:     /user
    defaults: { _controller: AdminLTEAdminBundle:User:index }