# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Umbrella\AdminBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       [ ROLE_USER ]
        ROLE_GODLIKE_ADMIN: [ ROLE_ADMIN ]

    providers:
        chain_provider:
            chain :
                providers: [in_memory, bo_provider]
        in_memory:
            memory:
                users:
                    root: { password: root, roles: [ 'ROLE_GODLIKE_ADMIN' ] }
        bo_provider:
            entity: { class: UmbrellaAdminBundle:User, property: username }

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }

    firewalls:
        dev:
            pattern:    ^/(_profiler|_wdt|css|js)
            security:   false

        bo_firewall:
              pattern: ^/admin/
              anonymous: ~
              form_login:
                  provider: bo_provider
                  login_path: admin_ltebo_homepage
                  check_path: umbrella_admin.login_check
                  remember_me: true
              logout: true