# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Umbrella\UserBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:           [ ROLE_USER ]
        ROLE_FORM_MANAGER:    [ ROLE_ADMIN ]
        ROLE_TABLE_MANAGER:   [ ROLE_ADMIN ]
        ROLE_USER_MANAGER:    [ ROLE_ADMIN ]
        ROLE_GODLIKE_ADMIN:   [ ROLE_USER_MANAGER, ROLE_TABLE_MANAGER, ROLE_FORM_MANAGER ]

    providers:
        bo_provider:
            chain :
                providers: [in_memory, in_db]
        in_memory:
            memory:
                users:
                    root: { password: root, roles: [ 'ROLE_GODLIKE_ADMIN' ] }
        in_db:
            entity: { class: UmbrellaUserBundle:User, property: username }

    access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }

    firewalls:
        dev:
            pattern:    ^/(_profiler|_wdt|css|js)
            security:   false

        bo_firewall:
              pattern: ^/admin/
              anonymous: ~
              form_login:
                  provider: bo_provider
                  login_path: umbrella_admin.login
                  check_path: umbrella_admin.login
                  default_target_path: admin.home
              logout:
                  path: umbrella_admin.logout
                  target: /admin