services:
    admin.menu_builder:
        class: Umbrella\AdminBundle\Builder\YmlMenuBuilder
        arguments: ["@service_container", 'AdminBundle/Resources/config/sitemap.yml']
        tags:
          - { name: umbrella_admin.menu_builder, method: createMenu, alias: default }
