parameters:
    admin.name: AdminLTE
    admin.html_name: <b>Admin</b>LTE
    admin.html_shortname: <b>A</b>LT
    admin.theme: skin-blue
    admin.sitemap: AdminLTE/AdminBundle/Resources/config/sitemap.yml