admin_ltebo_homepage:
    path:     /
    defaults: { _controller: AdminLTEBOBundle:Default:home }

admin_lte_form_general:
    path:     /form/general
    defaults: { _controller: AdminLTEBOBundle:Default:formGeneral }

admin_lte_form_advanced:
    path:     /form/advanced
    defaults: { _controller: AdminLTEBOBundle:Default:formAdvanced }

admin_lte_form_editors:
    path:     /form/editors
    defaults: { _controller: AdminLTEBOBundle:Default:formEditors }